# Site settings
title: Bahadır Coşkun
description: Kişisel Web Sitesi
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bahadır Coşkun
user_description: I am an electrical engineering student at Istanbul Technical University. I have been taking trainings to be a front-end developer for a long time. I supported these trainings I received along with the work I had done. 
user_title: 
email: 
# twitter_username: 
instagram_username: 
facebook_username: 
linkedin_username: bhdrcskn
github_username:  bhdrcskn
#medium_username: 
medium_url: https://medium.com/@bahadircoskun
# gplus_username:  

exclude: ['package.json', 'src' , 'node_modules']
