# Site settings
title: Bahadır Coşkun
description: Kişisel Web Sitesi
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bahadır Coşkun
user_description:  I'm an electrical engineering undergraduate student at Istanbul Technical University. I'm interested in software development and I'm working in this direction. You can find my work on GitHub.
user_title: 
email: 
# twitter_username: 
instagram_username: 
facebook_username: 
linkedin_username: bahadir-coskun
github_username:  bhdrcskn
#medium_username: 
medium_url: medium.com/@bahadircoskun
# gplus_username:  

exclude: ['package.json', 'src' , 'node_modules']
